package ifi.solution.model;
// Generated Mar 28, 2018 12:02:35 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Meter generated by hbm2java
 */
@Entity
@Table(name = "meter", catalog = "kurita")
public class Meter implements java.io.Serializable {

	private Integer id;
	private Parameter parameter;
	private double min;
	private double aver;
	private double max;
	private double stDev;
	private Date date;
	private Date time;

	public Meter() {
	}

	public Meter(Parameter parameter, double min, double aver, double max, double stDev, Date date, Date time) {
		this.parameter = parameter;
		this.min = min;
		this.aver = aver;
		this.max = max;
		this.stDev = stDev;
		this.date = date;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parameterId", nullable = false)
	public Parameter getParameter() {
		return this.parameter;
	}

	public void setParameter(Parameter parameter) {
		this.parameter = parameter;
	}

	@Column(name = "min", nullable = false, precision = 22, scale = 0)
	public double getMin() {
		return this.min;
	}

	public void setMin(double min) {
		this.min = min;
	}

	@Column(name = "aver", nullable = false, precision = 22, scale = 0)
	public double getAver() {
		return this.aver;
	}

	public void setAver(double aver) {
		this.aver = aver;
	}

	@Column(name = "max", nullable = false, precision = 22, scale = 0)
	public double getMax() {
		return this.max;
	}

	public void setMax(double max) {
		this.max = max;
	}

	@Column(name = "stDev", nullable = false, precision = 22, scale = 0)
	public double getStDev() {
		return this.stDev;
	}

	public void setStDev(double stDev) {
		this.stDev = stDev;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", nullable = false, length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
